### ISSUE TITLE
카테고리별 군집화

### ISSUE THREAD

**Issue by jovytree** [pladata-encore/DA36_mini2_olive_young#26]
## 🌈 Success criteria

1. product_name_x를 군집화
2. 군집화 결과와 secondary_category에 있는 12개 요소별 product_name_x의 분류 결과를 비교
3. product name으로 군집화가 얼마나 정확하게 되는지 확인해본다.

## 👷 To-do

- [x] 10:30 - 11:00 : scikit_lern에서 KMeans 설명 확인
- [x] 11:00 - 11:30 : _🙋‍♀️질문 > scikit learn의 텍스트 기반 KMeans 내용 토대로 product_name 군집화_ / **🧙답변 > 07_text_analysis의 02_document_clustering 확인해서 product_name을 count로 벡터화 한 뒤에 군집화. 하지만 mask인데 이름에 mask가 없으면 제대로 된 군집화가 안 될 것이고, 유의미한 결과가 아닐 수 있다. 사용할 수 있는 데이터를 얻으려면 ingrediant, highlight가 더 유의미해 보인다. 08_recommendation_system의 01_content_based_filtering 참고(literal_eval로 변환시킨 뒤에 공백 등을 요소로 해서 문자열 생성 -> 벡터라이즈 하면서 ngram도 썼고 공백 단위로 토큰화 한 다음에 빈도 수를 체크해서 벡터를 만들었음.**
- [x] 11:00 - 12:50 : 07_text_analysis의 02_document_clustering 참고해서 product_name_x KMeans 결과 확인
![Image](https://github.com/user-attachments/assets/07d87db5-2e0b-4f1d-9a43-d0d6f89eb3fe)

## 🧶 Review

문자열 전처리 후 ingrident 클러스터링을 진행하려고 했으나, 회의 후 조금 더 유의미한 작업에 시간을 할애하기로 결정됨. 여기서 마무리.
