### ISSUE TITLE
카테고리별 좋아요 순 제품 추천

### ISSUE THREAD

**Issue by jovytree** [pladata-encore/DA36_mini2_olive_young#27]
## 🌈 Success criteria

streamlit에서 추천 시스템 소개 전에 구현될 간단한 기능 추가

## 👷 To-do

- [x] functions.py의 def top3_love_count에 streamlit 실행 시 입력창에 '카테고리 이름'을 입력할 수 있게 하고, 카테고리별 '좋아요(love_count)' 1~3순위 제품의 제품명, 카테고리, 좋아요 개수, 하이라이트가 출력되도록 입력.
- [x] 카테고리에 없는 명칭을 적었을 경우 '없는 카테고리다'라는 안내가 나오도록 함.
- [x] main.py에서 streamlit 좌측 사이드바 목록에 들어갈 이름 수정 및 menu1.py에서 streamlit에 구현될 화면 수정

## 🧶 Review
![Image](https://github.com/user-attachments/assets/dc9e565a-03c2-4fc0-abc2-8c6a2835941c)
